###################################
#       Variables and Paths       #
###################################

# Specify the path to the LoopTools library:
PWD=$(strip $(shell pwd))
LT=$(PWD)/LoopTools-2.12/i686-CYGWIN_NT-6.1-WOW
LTCOMP = $(LT)/bin/fcc
IFlags = -I$(LT)/include
LFlags = -L$(LT)/lib -looptools

# Choose your compiler:
FCOMP = gfortran

# Do NOT change anything below this line by hand!
SELFENERGIESUSU = BuildingBlocks/SelfEnergies/Usual
SELFENERGIESALT = BuildingBlocks/SelfEnergies/Alternative
SELFENERGIESDERIV = BuildingBlocks/SelfEnergiesDerivatives
PROCESSDEPENDENTSCHEME = BuildingBlocks/ProcessDependentScheme
PARAMETERS = Parameters
TADPOLES = BuildingBlocks/Tadpoles
PROCESSA0TOBBBAR = BuildingBlocks/Processes/A0toBBBar
PROCESSA0TOCCBAR = BuildingBlocks/Processes/A0toCCBar
PROCESSA0TODDBAR = BuildingBlocks/Processes/A0toDDBar
PROCESSA0TOELELBAR = BuildingBlocks/Processes/A0toElElBar
PROCESSA0TOHHZ0 = BuildingBlocks/Processes/A0toHHZ0
PROCESSA0TOHMWP = BuildingBlocks/Processes/A0toHmWp
PROCESSA0TOMUMUBAR = BuildingBlocks/Processes/A0toMuMuBar
PROCESSA0TOSSBAR = BuildingBlocks/Processes/A0toSSBar
PROCESSA0TOTAUTAUBAR = BuildingBlocks/Processes/A0toTauTauBar
PROCESSA0TOTTBAR = BuildingBlocks/Processes/A0toTTBar
PROCESSA0TOUUBAR = BuildingBlocks/Processes/A0toUUBar
PROCESSA0TOZ0H0 = BuildingBlocks/Processes/A0toZ0h0
PROCESSH0TOA0A0 = BuildingBlocks/Processes/h0toA0A0
PROCESSH0TOA0Z0 = BuildingBlocks/Processes/h0toA0Z0
PROCESSH0TOBBBAR = BuildingBlocks/Processes/h0toBBBar
PROCESSH0TOCCBAR = BuildingBlocks/Processes/h0toCCBar
PROCESSH0TODDBAR = BuildingBlocks/Processes/h0toDDBar
PROCESSH0TOELELBAR = BuildingBlocks/Processes/h0toElElBar
PROCESSH0TOHHHH = BuildingBlocks/Processes/h0toHHHH
PROCESSH0TOHMHP = BuildingBlocks/Processes/h0toHmHp
PROCESSH0TOHPWM = BuildingBlocks/Processes/h0toHpWm
PROCESSH0TOMUMUBAR = BuildingBlocks/Processes/h0toMuMuBar
PROCESSH0TOSSBAR = BuildingBlocks/Processes/h0toSSBar
PROCESSH0TOTAUTAUBAR = BuildingBlocks/Processes/h0toTauTauBar
PROCESSH0TOTTBAR = BuildingBlocks/Processes/h0toTTBar
PROCESSH0TOUUBAR = BuildingBlocks/Processes/h0toUUBar
PROCESSH0TOWMWP = BuildingBlocks/Processes/h0toWmWp
PROCESSH0TOZ0Z0 = BuildingBlocks/Processes/h0toZ0Z0
PROCESSHHTOA0A0 = BuildingBlocks/Processes/HHtoA0A0
PROCESSHHTOA0Z0 = BuildingBlocks/Processes/HHtoA0Z0
PROCESSHHTOBBBAR = BuildingBlocks/Processes/HHtoBBBar
PROCESSHHTOCCBAR = BuildingBlocks/Processes/HHtoCCBar
PROCESSHHTODDBAR = BuildingBlocks/Processes/HHtoDDBar
PROCESSHHTOELELBAR = BuildingBlocks/Processes/HHtoElElBar
PROCESSHHTOH0H0 = BuildingBlocks/Processes/HHtoh0h0
PROCESSHHTOHMHP = BuildingBlocks/Processes/HHtoHmHp
PROCESSHHTOHPWM = BuildingBlocks/Processes/HHtoHpWm
PROCESSHHTOMUMUBAR = BuildingBlocks/Processes/HHtoMuMuBar
PROCESSHHTOSSBAR = BuildingBlocks/Processes/HHtoSSBar
PROCESSHHTOTAUTAUBAR = BuildingBlocks/Processes/HHtoTauTauBar
PROCESSHHTOTTBAR = BuildingBlocks/Processes/HHtoTTBar
PROCESSHHTOUUBAR = BuildingBlocks/Processes/HHtoUUBar
PROCESSHHTOWMWP = BuildingBlocks/Processes/HHtoWmWp
PROCESSHHTOZ0Z0 = BuildingBlocks/Processes/HHtoZ0Z0
PROCESSHPTOA0WP = BuildingBlocks/Processes/HptoA0Wp
PROCESSHPTOBBARC = BuildingBlocks/Processes/HptoBBarC
PROCESSHPTOBBART = BuildingBlocks/Processes/HptoBBarT
PROCESSHPTOBBARU = BuildingBlocks/Processes/HptoBBarU
PROCESSHPTOCDBAR = BuildingBlocks/Processes/HptoCDBar
PROCESSHPTOCSBAR = BuildingBlocks/Processes/HptoCSBar
PROCESSHPTODBART = BuildingBlocks/Processes/HptoDBarT
PROCESSHPTODBARU = BuildingBlocks/Processes/HptoDBarU
PROCESSHPTOELBARNEUE = BuildingBlocks/Processes/HptoElBarNeuE
PROCESSHPTOHHWP = BuildingBlocks/Processes/HptoHHWp
PROCESSHPTOMUBARNEUM = BuildingBlocks/Processes/HptoMuBarNeuM
PROCESSHPTONEUTTAUBAR = BuildingBlocks/Processes/HptoNeuTTauBar
PROCESSHPTOSBART = BuildingBlocks/Processes/HptoSBarT
PROCESSHPTOSBARU = BuildingBlocks/Processes/HptoSBarU
PROCESSHPTOWPH0 = BuildingBlocks/Processes/HptoWph0

%.o: %.F90
	$(LTCOMP) -c -o $@ $< $(IFlags)

$(SELFENERGIESALT)/%.o: $(SELFENERGIESALT)/%.F90 constants.o
	$(LTCOMP) -c -o $@ $< $(IFlags)

$(SELFENERGIESUSU)/%.o: $(SELFENERGIESUSU)/%.F90 constants.o
	$(LTCOMP) -c -o $@ $< $(IFlags)

$(SELFENERGIESDERIV)/%.o: $(SELFENERGIESDERIV)/%.F90 constants.o
	$(LTCOMP) -c -o $@ $< $(IFlags)

$(PROCESSDEPENDENTSCHEME)/%.o: $(PROCESSDEPENDENTSCHEME)/%.F90 constants.o
	$(LTCOMP) -c -o $@ $< $(IFlags)

$(TADPOLES)/%.o: $(TADPOLES)/%.F90 constants.o
	$(LTCOMP) -c -o $@ $< $(IFlags)

$(PROCESSA0TOBBBAR)/%.o: $(PROCESSA0TOBBBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSA0TOCCBAR)/%.o: $(PROCESSA0TOCCBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSA0TODDBAR)/%.o: $(PROCESSA0TODDBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSA0TOELELBAR)/%.o: $(PROCESSA0TOELELBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSA0TOHHZ0)/%.o: $(PROCESSA0TOHHZ0)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSA0TOHMWP)/%.o: $(PROCESSA0TOHMWP)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSA0TOMUMUBAR)/%.o: $(PROCESSA0TOMUMUBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSA0TOSSBAR)/%.o: $(PROCESSA0TOSSBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSA0TOTAUTAUBAR)/%.o: $(PROCESSA0TOTAUTAUBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSA0TOTTBAR)/%.o: $(PROCESSA0TOTTBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSA0TOUUBAR)/%.o: $(PROCESSA0TOUUBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSA0TOZ0H0)/%.o: $(PROCESSA0TOZ0H0)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOA0A0)/%.o: $(PROCESSH0TOA0A0)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOA0Z0)/%.o: $(PROCESSH0TOA0Z0)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOBBBAR)/%.o: $(PROCESSH0TOBBBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOCCBAR)/%.o: $(PROCESSH0TOCCBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TODDBAR)/%.o: $(PROCESSH0TODDBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOELELBAR)/%.o: $(PROCESSH0TOELELBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOHHHH)/%.o: $(PROCESSH0TOHHHH)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOHMHP)/%.o: $(PROCESSH0TOHMHP)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOHPWM)/%.o: $(PROCESSH0TOHPWM)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOMUMUBAR)/%.o: $(PROCESSH0TOMUMUBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOSSBAR)/%.o: $(PROCESSH0TOSSBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOTAUTAUBAR)/%.o: $(PROCESSH0TOTAUTAUBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOTTBAR)/%.o: $(PROCESSH0TOTTBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOUUBAR)/%.o: $(PROCESSH0TOUUBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOWMWP)/%.o: $(PROCESSH0TOWMWP)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSH0TOZ0Z0)/%.o: $(PROCESSH0TOZ0Z0)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOA0A0)/%.o: $(PROCESSHHTOA0A0)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOA0Z0)/%.o: $(PROCESSHHTOA0Z0)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOBBBAR)/%.o: $(PROCESSHHTOBBBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOCCBAR)/%.o: $(PROCESSHHTOCCBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTODDBAR)/%.o: $(PROCESSHHTODDBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOELELBAR)/%.o: $(PROCESSHHTOELELBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOH0H0)/%.o: $(PROCESSHHTOH0H0)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOHMHP)/%.o: $(PROCESSHHTOHMHP)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOHPWM)/%.o: $(PROCESSHHTOHPWM)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOMUMUBAR)/%.o: $(PROCESSHHTOMUMUBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOSSBAR)/%.o: $(PROCESSHHTOSSBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOTAUTAUBAR)/%.o: $(PROCESSHHTOTAUTAUBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOTTBAR)/%.o: $(PROCESSHHTOTTBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOUUBAR)/%.o: $(PROCESSHHTOUUBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOWMWP)/%.o: $(PROCESSHHTOWMWP)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHHTOZ0Z0)/%.o: $(PROCESSHHTOZ0Z0)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTOA0WP)/%.o: $(PROCESSHPTOA0WP)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTOBBARC)/%.o: $(PROCESSHPTOBBARC)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTOBBART)/%.o: $(PROCESSHPTOBBART)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTOBBARU)/%.o: $(PROCESSHPTOBBARU)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTOCDBAR)/%.o: $(PROCESSHPTOCDBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTOCSBAR)/%.o: $(PROCESSHPTOCSBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTODBART)/%.o: $(PROCESSHPTODBART)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTODBARU)/%.o: $(PROCESSHPTODBARU)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTOELBARNEUE)/%.o: $(PROCESSHPTOELBARNEUE)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTOHHWP)/%.o: $(PROCESSHPTOHHWP)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTOMUBARNEUM)/%.o: $(PROCESSHPTOMUBARNEUM)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTONEUTTAUBAR)/%.o: $(PROCESSHPTONEUTTAUBAR)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTOSBART)/%.o: $(PROCESSHPTOSBART)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTOSBARU)/%.o: $(PROCESSHPTOSBARU)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)
$(PROCESSHPTOWPH0)/%.o: $(PROCESSHPTOWPH0)/%.F90 constants.o counterterms.o
	$(LTCOMP) -c -o $@ $< $(IFlags)

$(PARAMETERS)/%.o: $(PARAMETERS)/%.F90 constants.o
	$(LTCOMP) -c -o $@ $< $(IFlags)

electroweakCorrections: constants.o $(SELFENERGIESUSU)/SelfAA.o $(SELFENERGIESUSU)/SelfAALight.o $(SELFENERGIESUSU)/SelfWpWp.o $(SELFENERGIESUSU)/SelfZ0Z0.o \
	$(SELFENERGIESUSU)/SelfAZ0.o $(SELFENERGIESUSU)/SelfAZ0ZeroMom.o $(SELFENERGIESALT)/SelfAA.o $(SELFENERGIESALT)/SelfWpWp.o $(SELFENERGIESALT)/SelfZ0Z0.o \
	$(SELFENERGIESALT)/SelfAZ0.o $(SELFENERGIESALT)/SelfAZ0ZeroMom.o $(SELFENERGIESUSU)/SelfA0A0.o $(SELFENERGIESUSU)/SelfG0A0.o \
	$(SELFENERGIESUSU)/SelfG0G0.o $(SELFENERGIESUSU)/SelfGpGp.o $(SELFENERGIESUSU)/SelfGpHp.o $(SELFENERGIESUSU)/Selfh0h0.o $(SELFENERGIESUSU)/SelfHHh0.o \
	$(SELFENERGIESUSU)/SelfHHHH.o $(SELFENERGIESUSU)/SelfHpHp.o $(SELFENERGIESALT)/SelfA0A0.o $(SELFENERGIESALT)/SelfG0A0.o $(SELFENERGIESALT)/SelfG0G0.o \
	$(SELFENERGIESALT)/SelfGpGp.o $(SELFENERGIESALT)/SelfGpHp.o $(SELFENERGIESALT)/Selfh0h0.o $(SELFENERGIESALT)/SelfHHh0.o $(SELFENERGIESALT)/SelfHHHH.o \
	$(SELFENERGIESALT)/SelfHpHp.o $(SELFENERGIESDERIV)/DSelfAA.o $(SELFENERGIESDERIV)/DSelfAALight.o $(SELFENERGIESDERIV)/DSelfWpWp.o $(SELFENERGIESDERIV)/DSelfZ0Z0.o \
	$(SELFENERGIESDERIV)/DSelfAZ0.o $(SELFENERGIESDERIV)/DSelfA0A0.o $(SELFENERGIESDERIV)/DSelfG0A0.o $(SELFENERGIESDERIV)/DSelfG0G0.o $(SELFENERGIESDERIV)/DSelfGpGp.o \
	$(SELFENERGIESDERIV)/DSelfGpHp.o $(SELFENERGIESDERIV)/DSelfHpHp.o $(SELFENERGIESDERIV)/DSelfh0h0.o $(SELFENERGIESDERIV)/DSelfHHh0.o $(SELFENERGIESDERIV)/DSelfHHHH.o \
	$(SELFENERGIESALT)/SelfHHh0Add.o $(SELFENERGIESALT)/SelfG0A0Add.o $(SELFENERGIESALT)/SelfGpHpAdd.o $(TADPOLES)/TadHH.o $(TADPOLES)/Tadh0.o \
	$(SELFENERGIESUSU)/SelfNeuENeuELeft.o $(SELFENERGIESUSU)/SelfNeuENeuERight.o $(SELFENERGIESUSU)/SelfNeuENeuEScalar.o \
	$(SELFENERGIESUSU)/SelfNeuMNeuMLeft.o $(SELFENERGIESUSU)/SelfNeuMNeuMRight.o $(SELFENERGIESUSU)/SelfNeuMNeuMScalar.o \
	$(SELFENERGIESUSU)/SelfNeuTNeuTLeft.o $(SELFENERGIESUSU)/SelfNeuTNeuTRight.o $(SELFENERGIESUSU)/SelfNeuTNeuTScalar.o \
	$(SELFENERGIESUSU)/SelfElElLeft.o $(SELFENERGIESUSU)/SelfElElRight.o $(SELFENERGIESUSU)/SelfElElScalar.o \
	$(SELFENERGIESUSU)/SelfMuMuLeft.o $(SELFENERGIESUSU)/SelfMuMuRight.o $(SELFENERGIESUSU)/SelfMuMuScalar.o \
	$(SELFENERGIESUSU)/SelfTauTauLeft.o $(SELFENERGIESUSU)/SelfTauTauRight.o $(SELFENERGIESUSU)/SelfTauTauScalar.o \
	$(SELFENERGIESUSU)/SelfTauTauLeftQED.o $(SELFENERGIESUSU)/SelfTauTauRightQED.o $(SELFENERGIESUSU)/SelfTauTauScalarQED.o \
	$(SELFENERGIESUSU)/SelfTauTauLeftWeak.o $(SELFENERGIESUSU)/SelfTauTauRightWeak.o $(SELFENERGIESUSU)/SelfTauTauScalarWeak.o \
	$(SELFENERGIESUSU)/SelfDDLeft.o $(SELFENERGIESUSU)/SelfDDRight.o $(SELFENERGIESUSU)/SelfDDScalar.o \
	$(SELFENERGIESUSU)/SelfUULeft.o $(SELFENERGIESUSU)/SelfUURight.o $(SELFENERGIESUSU)/SelfUUScalar.o \
	$(SELFENERGIESUSU)/SelfSSLeft.o $(SELFENERGIESUSU)/SelfSSRight.o $(SELFENERGIESUSU)/SelfSSScalar.o \
	$(SELFENERGIESUSU)/SelfCCLeft.o $(SELFENERGIESUSU)/SelfCCRight.o $(SELFENERGIESUSU)/SelfCCScalar.o \
	$(SELFENERGIESUSU)/SelfBBLeft.o $(SELFENERGIESUSU)/SelfBBRight.o $(SELFENERGIESUSU)/SelfBBScalar.o \
	$(SELFENERGIESUSU)/SelfTTLeft.o $(SELFENERGIESUSU)/SelfTTRight.o $(SELFENERGIESUSU)/SelfTTScalar.o \
	$(SELFENERGIESUSU)/SelfUCLeft.o $(SELFENERGIESUSU)/SelfUCRight.o $(SELFENERGIESUSU)/SelfUCScalar.o \
	$(SELFENERGIESUSU)/SelfUTLeft.o $(SELFENERGIESUSU)/SelfUTRight.o $(SELFENERGIESUSU)/SelfUTScalar.o \
	$(SELFENERGIESUSU)/SelfCTLeft.o $(SELFENERGIESUSU)/SelfCTRight.o $(SELFENERGIESUSU)/SelfCTScalar.o \
	$(SELFENERGIESUSU)/SelfDSLeft.o $(SELFENERGIESUSU)/SelfDSRight.o $(SELFENERGIESUSU)/SelfDSScalar.o \
	$(SELFENERGIESUSU)/SelfDBLeft.o $(SELFENERGIESUSU)/SelfDBRight.o $(SELFENERGIESUSU)/SelfDBScalar.o \
	$(SELFENERGIESUSU)/SelfSBLeft.o $(SELFENERGIESUSU)/SelfSBRight.o $(SELFENERGIESUSU)/SelfSBScalar.o \
	$(SELFENERGIESALT)/SelfNeuENeuELeft.o $(SELFENERGIESALT)/SelfNeuENeuERight.o $(SELFENERGIESALT)/SelfNeuENeuEScalar.o \
	$(SELFENERGIESALT)/SelfNeuMNeuMLeft.o $(SELFENERGIESALT)/SelfNeuMNeuMRight.o $(SELFENERGIESALT)/SelfNeuMNeuMScalar.o \
	$(SELFENERGIESALT)/SelfNeuTNeuTLeft.o $(SELFENERGIESALT)/SelfNeuTNeuTRight.o $(SELFENERGIESALT)/SelfNeuTNeuTScalar.o \
	$(SELFENERGIESALT)/SelfElElLeft.o $(SELFENERGIESALT)/SelfElElRight.o $(SELFENERGIESALT)/SelfElElScalar.o \
	$(SELFENERGIESALT)/SelfMuMuLeft.o $(SELFENERGIESALT)/SelfMuMuRight.o $(SELFENERGIESALT)/SelfMuMuScalar.o \
	$(SELFENERGIESALT)/SelfTauTauLeft.o $(SELFENERGIESALT)/SelfTauTauRight.o $(SELFENERGIESALT)/SelfTauTauScalar.o \
	$(SELFENERGIESALT)/SelfTauTauLeftQED.o $(SELFENERGIESALT)/SelfTauTauRightQED.o $(SELFENERGIESALT)/SelfTauTauScalarQED.o \
	$(SELFENERGIESALT)/SelfTauTauLeftWeak.o $(SELFENERGIESALT)/SelfTauTauRightWeak.o $(SELFENERGIESALT)/SelfTauTauScalarWeak.o \
	$(SELFENERGIESALT)/SelfDDLeft.o $(SELFENERGIESALT)/SelfDDRight.o $(SELFENERGIESALT)/SelfDDScalar.o \
	$(SELFENERGIESALT)/SelfUULeft.o $(SELFENERGIESALT)/SelfUURight.o $(SELFENERGIESALT)/SelfUUScalar.o \
	$(SELFENERGIESALT)/SelfSSLeft.o $(SELFENERGIESALT)/SelfSSRight.o $(SELFENERGIESALT)/SelfSSScalar.o \
	$(SELFENERGIESALT)/SelfCCLeft.o $(SELFENERGIESALT)/SelfCCRight.o $(SELFENERGIESALT)/SelfCCScalar.o \
	$(SELFENERGIESALT)/SelfBBLeft.o $(SELFENERGIESALT)/SelfBBRight.o $(SELFENERGIESALT)/SelfBBScalar.o \
	$(SELFENERGIESALT)/SelfTTLeft.o $(SELFENERGIESALT)/SelfTTRight.o $(SELFENERGIESALT)/SelfTTScalar.o \
	$(SELFENERGIESALT)/SelfUCLeft.o $(SELFENERGIESALT)/SelfUCRight.o $(SELFENERGIESALT)/SelfUCScalar.o \
	$(SELFENERGIESALT)/SelfUTLeft.o $(SELFENERGIESALT)/SelfUTRight.o $(SELFENERGIESALT)/SelfUTScalar.o \
	$(SELFENERGIESALT)/SelfCTLeft.o $(SELFENERGIESALT)/SelfCTRight.o $(SELFENERGIESALT)/SelfCTScalar.o \
	$(SELFENERGIESALT)/SelfDSLeft.o $(SELFENERGIESALT)/SelfDSRight.o $(SELFENERGIESALT)/SelfDSScalar.o \
	$(SELFENERGIESALT)/SelfDBLeft.o $(SELFENERGIESALT)/SelfDBRight.o $(SELFENERGIESALT)/SelfDBScalar.o \
	$(SELFENERGIESALT)/SelfSBLeft.o $(SELFENERGIESALT)/SelfSBRight.o $(SELFENERGIESALT)/SelfSBScalar.o \
	$(SELFENERGIESDERIV)/DSelfNeuENeuELeft.o $(SELFENERGIESDERIV)/DSelfNeuENeuERight.o $(SELFENERGIESDERIV)/DSelfNeuENeuEScalar.o \
	$(SELFENERGIESDERIV)/DSelfNeuMNeuMLeft.o $(SELFENERGIESDERIV)/DSelfNeuMNeuMRight.o $(SELFENERGIESDERIV)/DSelfNeuMNeuMScalar.o \
	$(SELFENERGIESDERIV)/DSelfNeuTNeuTLeft.o $(SELFENERGIESDERIV)/DSelfNeuTNeuTRight.o $(SELFENERGIESDERIV)/DSelfNeuTNeuTScalar.o \
	$(SELFENERGIESDERIV)/DSelfElElLeft.o $(SELFENERGIESDERIV)/DSelfElElRight.o $(SELFENERGIESDERIV)/DSelfElElScalar.o \
	$(SELFENERGIESDERIV)/DSelfMuMuLeft.o $(SELFENERGIESDERIV)/DSelfMuMuRight.o $(SELFENERGIESDERIV)/DSelfMuMuScalar.o \
	$(SELFENERGIESDERIV)/DSelfTauTauLeft.o $(SELFENERGIESDERIV)/DSelfTauTauRight.o $(SELFENERGIESDERIV)/DSelfTauTauScalar.o \
	$(SELFENERGIESDERIV)/DSelfTauTauLeftQED.o $(SELFENERGIESDERIV)/DSelfTauTauRightQED.o $(SELFENERGIESDERIV)/DSelfTauTauScalarQED.o \
	$(SELFENERGIESDERIV)/DSelfTauTauLeftWeak.o $(SELFENERGIESDERIV)/DSelfTauTauRightWeak.o $(SELFENERGIESDERIV)/DSelfTauTauScalarWeak.o \
	$(SELFENERGIESDERIV)/DSelfDDLeft.o $(SELFENERGIESDERIV)/DSelfDDRight.o $(SELFENERGIESDERIV)/DSelfDDScalar.o \
	$(SELFENERGIESDERIV)/DSelfUULeft.o $(SELFENERGIESDERIV)/DSelfUURight.o $(SELFENERGIESDERIV)/DSelfUUScalar.o \
	$(SELFENERGIESDERIV)/DSelfSSLeft.o $(SELFENERGIESDERIV)/DSelfSSRight.o $(SELFENERGIESDERIV)/DSelfSSScalar.o \
	$(SELFENERGIESDERIV)/DSelfCCLeft.o $(SELFENERGIESDERIV)/DSelfCCRight.o $(SELFENERGIESDERIV)/DSelfCCScalar.o \
	$(SELFENERGIESDERIV)/DSelfBBLeft.o $(SELFENERGIESDERIV)/DSelfBBRight.o $(SELFENERGIESDERIV)/DSelfBBScalar.o \
	$(SELFENERGIESDERIV)/DSelfTTLeft.o $(SELFENERGIESDERIV)/DSelfTTRight.o $(SELFENERGIESDERIV)/DSelfTTScalar.o \
	$(SELFENERGIESDERIV)/DSelfUCLeft.o $(SELFENERGIESDERIV)/DSelfUCRight.o $(SELFENERGIESDERIV)/DSelfUCScalar.o \
	$(SELFENERGIESDERIV)/DSelfUTLeft.o $(SELFENERGIESDERIV)/DSelfUTRight.o $(SELFENERGIESDERIV)/DSelfUTScalar.o \
	$(SELFENERGIESDERIV)/DSelfCTLeft.o $(SELFENERGIESDERIV)/DSelfCTRight.o $(SELFENERGIESDERIV)/DSelfCTScalar.o \
	$(SELFENERGIESDERIV)/DSelfDSLeft.o $(SELFENERGIESDERIV)/DSelfDSRight.o $(SELFENERGIESDERIV)/DSelfDSScalar.o \
	$(SELFENERGIESDERIV)/DSelfDBLeft.o $(SELFENERGIESDERIV)/DSelfDBRight.o $(SELFENERGIESDERIV)/DSelfDBScalar.o \
	$(SELFENERGIESDERIV)/DSelfSBLeft.o $(SELFENERGIESDERIV)/DSelfSBRight.o $(SELFENERGIESDERIV)/DSelfSBScalar.o \
	$(PROCESSDEPENDENTSCHEME)/A0toTauPTauMProcDepVC.o $(PROCESSDEPENDENTSCHEME)/HHtoTauPTauMProcDepVC.o $(PROCESSDEPENDENTSCHEME)/h0toTauPTauMProcDepVC.o \
	$(PROCESSA0TOBBBAR)/TreeLevelWidthRed.o $(PROCESSA0TOBBBAR)/NLOWidthRed.o $(PROCESSA0TOBBBAR)/NLOTadWidthRed.o $(PROCESSA0TOBBBAR)/Counterterm.o $(PROCESSA0TOBBBAR)/RealCorrections.o \
	$(PROCESSA0TOCCBAR)/TreeLevelWidthRed.o $(PROCESSA0TOCCBAR)/NLOWidthRed.o $(PROCESSA0TOCCBAR)/NLOTadWidthRed.o $(PROCESSA0TOCCBAR)/Counterterm.o $(PROCESSA0TOCCBAR)/RealCorrections.o \
	$(PROCESSA0TODDBAR)/TreeLevelWidthRed.o $(PROCESSA0TODDBAR)/NLOWidthRed.o $(PROCESSA0TODDBAR)/NLOTadWidthRed.o $(PROCESSA0TODDBAR)/Counterterm.o $(PROCESSA0TODDBAR)/RealCorrections.o \
	$(PROCESSA0TOELELBAR)/TreeLevelWidthRed.o $(PROCESSA0TOELELBAR)/NLOWidthRed.o $(PROCESSA0TOELELBAR)/NLOTadWidthRed.o $(PROCESSA0TOELELBAR)/Counterterm.o $(PROCESSA0TOELELBAR)/RealCorrections.o \
	$(PROCESSA0TOHHZ0)/TreeLevelWidthRed.o $(PROCESSA0TOHHZ0)/NLOWidthRed.o $(PROCESSA0TOHHZ0)/NLOTadWidthRed.o $(PROCESSA0TOHHZ0)/Counterterm.o $(PROCESSA0TOHHZ0)/RealCorrections.o \
	$(PROCESSA0TOHMWP)/TreeLevelWidthRed.o $(PROCESSA0TOHMWP)/NLOWidthRed.o $(PROCESSA0TOHMWP)/NLOTadWidthRed.o $(PROCESSA0TOHMWP)/Counterterm.o $(PROCESSA0TOHMWP)/RealCorrections.o \
	$(PROCESSA0TOMUMUBAR)/TreeLevelWidthRed.o $(PROCESSA0TOMUMUBAR)/NLOWidthRed.o $(PROCESSA0TOMUMUBAR)/NLOTadWidthRed.o $(PROCESSA0TOMUMUBAR)/Counterterm.o $(PROCESSA0TOMUMUBAR)/RealCorrections.o \
	$(PROCESSA0TOSSBAR)/TreeLevelWidthRed.o $(PROCESSA0TOSSBAR)/NLOWidthRed.o $(PROCESSA0TOSSBAR)/NLOTadWidthRed.o $(PROCESSA0TOSSBAR)/Counterterm.o $(PROCESSA0TOSSBAR)/RealCorrections.o \
	$(PROCESSA0TOTAUTAUBAR)/TreeLevelWidthRed.o $(PROCESSA0TOTAUTAUBAR)/NLOWidthRed.o $(PROCESSA0TOTAUTAUBAR)/NLOTadWidthRed.o $(PROCESSA0TOTAUTAUBAR)/Counterterm.o $(PROCESSA0TOTAUTAUBAR)/RealCorrections.o \
	$(PROCESSA0TOTTBAR)/TreeLevelWidthRed.o $(PROCESSA0TOTTBAR)/NLOWidthRed.o $(PROCESSA0TOTTBAR)/NLOTadWidthRed.o $(PROCESSA0TOTTBAR)/Counterterm.o $(PROCESSA0TOTTBAR)/RealCorrections.o \
	$(PROCESSA0TOUUBAR)/TreeLevelWidthRed.o $(PROCESSA0TOUUBAR)/NLOWidthRed.o $(PROCESSA0TOUUBAR)/NLOTadWidthRed.o $(PROCESSA0TOUUBAR)/Counterterm.o $(PROCESSA0TOUUBAR)/RealCorrections.o \
	$(PROCESSA0TOZ0H0)/TreeLevelWidthRed.o $(PROCESSA0TOZ0H0)/NLOWidthRed.o $(PROCESSA0TOZ0H0)/NLOTadWidthRed.o $(PROCESSA0TOZ0H0)/Counterterm.o $(PROCESSA0TOZ0H0)/RealCorrections.o \
	$(PROCESSH0TOA0A0)/TreeLevelWidthRed.o $(PROCESSH0TOA0A0)/NLOWidthRed.o $(PROCESSH0TOA0A0)/NLOTadWidthRed.o $(PROCESSH0TOA0A0)/Counterterm.o $(PROCESSH0TOA0A0)/RealCorrections.o \
	$(PROCESSH0TOA0Z0)/TreeLevelWidthRed.o $(PROCESSH0TOA0Z0)/NLOWidthRed.o $(PROCESSH0TOA0Z0)/NLOTadWidthRed.o $(PROCESSH0TOA0Z0)/Counterterm.o $(PROCESSH0TOA0Z0)/RealCorrections.o \
	$(PROCESSH0TOBBBAR)/TreeLevelWidthRed.o $(PROCESSH0TOBBBAR)/NLOWidthRed.o $(PROCESSH0TOBBBAR)/NLOTadWidthRed.o $(PROCESSH0TOBBBAR)/Counterterm.o $(PROCESSH0TOBBBAR)/RealCorrections.o \
	$(PROCESSH0TOCCBAR)/TreeLevelWidthRed.o $(PROCESSH0TOCCBAR)/NLOWidthRed.o $(PROCESSH0TOCCBAR)/NLOTadWidthRed.o $(PROCESSH0TOCCBAR)/Counterterm.o $(PROCESSH0TOCCBAR)/RealCorrections.o \
	$(PROCESSH0TODDBAR)/TreeLevelWidthRed.o $(PROCESSH0TODDBAR)/NLOWidthRed.o $(PROCESSH0TODDBAR)/NLOTadWidthRed.o $(PROCESSH0TODDBAR)/Counterterm.o $(PROCESSH0TODDBAR)/RealCorrections.o \
	$(PROCESSH0TOELELBAR)/TreeLevelWidthRed.o $(PROCESSH0TOELELBAR)/NLOWidthRed.o $(PROCESSH0TOELELBAR)/NLOTadWidthRed.o $(PROCESSH0TOELELBAR)/Counterterm.o $(PROCESSH0TOELELBAR)/RealCorrections.o \
	$(PROCESSH0TOHHHH)/TreeLevelWidthRed.o $(PROCESSH0TOHHHH)/NLOWidthRed.o $(PROCESSH0TOHHHH)/NLOTadWidthRed.o $(PROCESSH0TOHHHH)/Counterterm.o $(PROCESSH0TOHHHH)/RealCorrections.o \
	$(PROCESSH0TOHMHP)/TreeLevelWidthRed.o $(PROCESSH0TOHMHP)/NLOWidthRed.o $(PROCESSH0TOHMHP)/NLOTadWidthRed.o $(PROCESSH0TOHMHP)/Counterterm.o $(PROCESSH0TOHMHP)/RealCorrections.o \
	$(PROCESSH0TOHPWM)/TreeLevelWidthRed.o $(PROCESSH0TOHPWM)/NLOWidthRed.o $(PROCESSH0TOHPWM)/NLOTadWidthRed.o $(PROCESSH0TOHPWM)/Counterterm.o $(PROCESSH0TOHPWM)/RealCorrections.o \
	$(PROCESSH0TOMUMUBAR)/TreeLevelWidthRed.o $(PROCESSH0TOMUMUBAR)/NLOWidthRed.o $(PROCESSH0TOMUMUBAR)/NLOTadWidthRed.o $(PROCESSH0TOMUMUBAR)/Counterterm.o $(PROCESSH0TOMUMUBAR)/RealCorrections.o \
	$(PROCESSH0TOSSBAR)/TreeLevelWidthRed.o $(PROCESSH0TOSSBAR)/NLOWidthRed.o $(PROCESSH0TOSSBAR)/NLOTadWidthRed.o $(PROCESSH0TOSSBAR)/Counterterm.o $(PROCESSH0TOSSBAR)/RealCorrections.o \
	$(PROCESSH0TOTAUTAUBAR)/TreeLevelWidthRed.o $(PROCESSH0TOTAUTAUBAR)/NLOWidthRed.o $(PROCESSH0TOTAUTAUBAR)/NLOTadWidthRed.o $(PROCESSH0TOTAUTAUBAR)/Counterterm.o $(PROCESSH0TOTAUTAUBAR)/RealCorrections.o \
	$(PROCESSH0TOTTBAR)/TreeLevelWidthRed.o $(PROCESSH0TOTTBAR)/NLOWidthRed.o $(PROCESSH0TOTTBAR)/NLOTadWidthRed.o $(PROCESSH0TOTTBAR)/Counterterm.o $(PROCESSH0TOTTBAR)/RealCorrections.o \
	$(PROCESSH0TOUUBAR)/TreeLevelWidthRed.o $(PROCESSH0TOUUBAR)/NLOWidthRed.o $(PROCESSH0TOUUBAR)/NLOTadWidthRed.o $(PROCESSH0TOUUBAR)/Counterterm.o $(PROCESSH0TOUUBAR)/RealCorrections.o \
	$(PROCESSH0TOWMWP)/TreeLevelWidthRed.o $(PROCESSH0TOWMWP)/NLOWidthRed.o $(PROCESSH0TOWMWP)/NLOTadWidthRed.o $(PROCESSH0TOWMWP)/Counterterm.o $(PROCESSH0TOWMWP)/RealCorrections.o \
	$(PROCESSH0TOZ0Z0)/TreeLevelWidthRed.o $(PROCESSH0TOZ0Z0)/NLOWidthRed.o $(PROCESSH0TOZ0Z0)/NLOTadWidthRed.o $(PROCESSH0TOZ0Z0)/Counterterm.o $(PROCESSH0TOZ0Z0)/RealCorrections.o \
	$(PROCESSHHTOA0A0)/TreeLevelWidthRed.o $(PROCESSHHTOA0A0)/NLOWidthRed.o $(PROCESSHHTOA0A0)/NLOTadWidthRed.o $(PROCESSHHTOA0A0)/Counterterm.o $(PROCESSHHTOA0A0)/RealCorrections.o \
	$(PROCESSHHTOA0Z0)/TreeLevelWidthRed.o $(PROCESSHHTOA0Z0)/NLOWidthRed.o $(PROCESSHHTOA0Z0)/NLOTadWidthRed.o $(PROCESSHHTOA0Z0)/Counterterm.o $(PROCESSHHTOA0Z0)/RealCorrections.o \
	$(PROCESSHHTOBBBAR)/TreeLevelWidthRed.o $(PROCESSHHTOBBBAR)/NLOWidthRed.o $(PROCESSHHTOBBBAR)/NLOTadWidthRed.o $(PROCESSHHTOBBBAR)/Counterterm.o $(PROCESSHHTOBBBAR)/RealCorrections.o \
	$(PROCESSHHTOCCBAR)/TreeLevelWidthRed.o $(PROCESSHHTOCCBAR)/NLOWidthRed.o $(PROCESSHHTOCCBAR)/NLOTadWidthRed.o $(PROCESSHHTOCCBAR)/Counterterm.o $(PROCESSHHTOCCBAR)/RealCorrections.o \
	$(PROCESSHHTODDBAR)/TreeLevelWidthRed.o $(PROCESSHHTODDBAR)/NLOWidthRed.o $(PROCESSHHTODDBAR)/NLOTadWidthRed.o $(PROCESSHHTODDBAR)/Counterterm.o $(PROCESSHHTODDBAR)/RealCorrections.o \
	$(PROCESSHHTOELELBAR)/TreeLevelWidthRed.o $(PROCESSHHTOELELBAR)/NLOWidthRed.o $(PROCESSHHTOELELBAR)/NLOTadWidthRed.o $(PROCESSHHTOELELBAR)/Counterterm.o $(PROCESSHHTOELELBAR)/RealCorrections.o \
	$(PROCESSHHTOH0H0)/TreeLevelWidthRed.o $(PROCESSHHTOH0H0)/NLOWidthRed.o $(PROCESSHHTOH0H0)/NLOTadWidthRed.o $(PROCESSHHTOH0H0)/Counterterm.o $(PROCESSHHTOH0H0)/RealCorrections.o \
	$(PROCESSHHTOHMHP)/TreeLevelWidthRed.o $(PROCESSHHTOHMHP)/NLOWidthRed.o $(PROCESSHHTOHMHP)/NLOTadWidthRed.o $(PROCESSHHTOHMHP)/Counterterm.o $(PROCESSHHTOHMHP)/RealCorrections.o \
	$(PROCESSHHTOHPWM)/TreeLevelWidthRed.o $(PROCESSHHTOHPWM)/NLOWidthRed.o $(PROCESSHHTOHPWM)/NLOTadWidthRed.o $(PROCESSHHTOHPWM)/Counterterm.o $(PROCESSHHTOHPWM)/RealCorrections.o \
	$(PROCESSHHTOMUMUBAR)/TreeLevelWidthRed.o $(PROCESSHHTOMUMUBAR)/NLOWidthRed.o $(PROCESSHHTOMUMUBAR)/NLOTadWidthRed.o $(PROCESSHHTOMUMUBAR)/Counterterm.o $(PROCESSHHTOMUMUBAR)/RealCorrections.o \
	$(PROCESSHHTOSSBAR)/TreeLevelWidthRed.o $(PROCESSHHTOSSBAR)/NLOWidthRed.o $(PROCESSHHTOSSBAR)/NLOTadWidthRed.o $(PROCESSHHTOSSBAR)/Counterterm.o $(PROCESSHHTOSSBAR)/RealCorrections.o \
	$(PROCESSHHTOTAUTAUBAR)/TreeLevelWidthRed.o $(PROCESSHHTOTAUTAUBAR)/NLOWidthRed.o $(PROCESSHHTOTAUTAUBAR)/NLOTadWidthRed.o $(PROCESSHHTOTAUTAUBAR)/Counterterm.o $(PROCESSHHTOTAUTAUBAR)/RealCorrections.o \
	$(PROCESSHHTOTTBAR)/TreeLevelWidthRed.o $(PROCESSHHTOTTBAR)/NLOWidthRed.o $(PROCESSHHTOTTBAR)/NLOTadWidthRed.o $(PROCESSHHTOTTBAR)/Counterterm.o $(PROCESSHHTOTTBAR)/RealCorrections.o \
	$(PROCESSHHTOUUBAR)/TreeLevelWidthRed.o $(PROCESSHHTOUUBAR)/NLOWidthRed.o $(PROCESSHHTOUUBAR)/NLOTadWidthRed.o $(PROCESSHHTOUUBAR)/Counterterm.o $(PROCESSHHTOUUBAR)/RealCorrections.o \
	$(PROCESSHHTOWMWP)/TreeLevelWidthRed.o $(PROCESSHHTOWMWP)/NLOWidthRed.o $(PROCESSHHTOWMWP)/NLOTadWidthRed.o $(PROCESSHHTOWMWP)/Counterterm.o $(PROCESSHHTOWMWP)/RealCorrections.o \
	$(PROCESSHHTOZ0Z0)/TreeLevelWidthRed.o $(PROCESSHHTOZ0Z0)/NLOWidthRed.o $(PROCESSHHTOZ0Z0)/NLOTadWidthRed.o $(PROCESSHHTOZ0Z0)/Counterterm.o $(PROCESSHHTOZ0Z0)/RealCorrections.o \
	$(PROCESSHPTOA0WP)/TreeLevelWidthRed.o $(PROCESSHPTOA0WP)/NLOWidthRed.o $(PROCESSHPTOA0WP)/NLOTadWidthRed.o $(PROCESSHPTOA0WP)/Counterterm.o $(PROCESSHPTOA0WP)/RealCorrections.o \
	$(PROCESSHPTOBBARC)/TreeLevelWidthRed.o $(PROCESSHPTOBBARC)/NLOWidthRed.o $(PROCESSHPTOBBARC)/NLOTadWidthRed.o $(PROCESSHPTOBBARC)/Counterterm.o $(PROCESSHPTOBBARC)/RealCorrections.o \
	$(PROCESSHPTOBBART)/TreeLevelWidthRed.o $(PROCESSHPTOBBART)/NLOWidthRed.o $(PROCESSHPTOBBART)/NLOTadWidthRed.o $(PROCESSHPTOBBART)/Counterterm.o $(PROCESSHPTOBBART)/RealCorrections.o \
	$(PROCESSHPTOBBARU)/TreeLevelWidthRed.o $(PROCESSHPTOBBARU)/NLOWidthRed.o $(PROCESSHPTOBBARU)/NLOTadWidthRed.o $(PROCESSHPTOBBARU)/Counterterm.o $(PROCESSHPTOBBARU)/RealCorrections.o \
	$(PROCESSHPTOCDBAR)/TreeLevelWidthRed.o $(PROCESSHPTOCDBAR)/NLOWidthRed.o $(PROCESSHPTOCDBAR)/NLOTadWidthRed.o $(PROCESSHPTOCDBAR)/Counterterm.o $(PROCESSHPTOCDBAR)/RealCorrections.o \
	$(PROCESSHPTOCSBAR)/TreeLevelWidthRed.o $(PROCESSHPTOCSBAR)/NLOWidthRed.o $(PROCESSHPTOCSBAR)/NLOTadWidthRed.o $(PROCESSHPTOCSBAR)/Counterterm.o $(PROCESSHPTOCSBAR)/RealCorrections.o \
	$(PROCESSHPTODBART)/TreeLevelWidthRed.o $(PROCESSHPTODBART)/NLOWidthRed.o $(PROCESSHPTODBART)/NLOTadWidthRed.o $(PROCESSHPTODBART)/Counterterm.o $(PROCESSHPTODBART)/RealCorrections.o \
	$(PROCESSHPTODBARU)/TreeLevelWidthRed.o $(PROCESSHPTODBARU)/NLOWidthRed.o $(PROCESSHPTODBARU)/NLOTadWidthRed.o $(PROCESSHPTODBARU)/Counterterm.o $(PROCESSHPTODBARU)/RealCorrections.o \
	$(PROCESSHPTOELBARNEUE)/TreeLevelWidthRed.o $(PROCESSHPTOELBARNEUE)/NLOWidthRed.o $(PROCESSHPTOELBARNEUE)/NLOTadWidthRed.o $(PROCESSHPTOELBARNEUE)/Counterterm.o $(PROCESSHPTOELBARNEUE)/RealCorrections.o \
	$(PROCESSHPTOHHWP)/TreeLevelWidthRed.o $(PROCESSHPTOHHWP)/NLOWidthRed.o $(PROCESSHPTOHHWP)/NLOTadWidthRed.o $(PROCESSHPTOHHWP)/Counterterm.o $(PROCESSHPTOHHWP)/RealCorrections.o \
	$(PROCESSHPTOMUBARNEUM)/TreeLevelWidthRed.o $(PROCESSHPTOMUBARNEUM)/NLOWidthRed.o $(PROCESSHPTOMUBARNEUM)/NLOTadWidthRed.o $(PROCESSHPTOMUBARNEUM)/Counterterm.o $(PROCESSHPTOMUBARNEUM)/RealCorrections.o \
	$(PROCESSHPTONEUTTAUBAR)/TreeLevelWidthRed.o $(PROCESSHPTONEUTTAUBAR)/NLOWidthRed.o $(PROCESSHPTONEUTTAUBAR)/NLOTadWidthRed.o $(PROCESSHPTONEUTTAUBAR)/Counterterm.o $(PROCESSHPTONEUTTAUBAR)/RealCorrections.o \
	$(PROCESSHPTOSBART)/TreeLevelWidthRed.o $(PROCESSHPTOSBART)/NLOWidthRed.o $(PROCESSHPTOSBART)/NLOTadWidthRed.o $(PROCESSHPTOSBART)/Counterterm.o $(PROCESSHPTOSBART)/RealCorrections.o \
	$(PROCESSHPTOSBARU)/TreeLevelWidthRed.o $(PROCESSHPTOSBARU)/NLOWidthRed.o $(PROCESSHPTOSBARU)/NLOTadWidthRed.o $(PROCESSHPTOSBARU)/Counterterm.o $(PROCESSHPTOSBARU)/RealCorrections.o \
	$(PROCESSHPTOWPH0)/TreeLevelWidthRed.o $(PROCESSHPTOWPH0)/NLOWidthRed.o $(PROCESSHPTOWPH0)/NLOTadWidthRed.o $(PROCESSHPTOWPH0)/Counterterm.o $(PROCESSHPTOWPH0)/RealCorrections.o \
	counterterms.o $(PARAMETERS)/getParameters.o electroweakCorrections.o
	$(LTCOMP) $(IFlags) constants.o $(SELFENERGIESUSU)/SelfAA.o $(SELFENERGIESUSU)/SelfAALight.o $(SELFENERGIESUSU)/SelfWpWp.o $(SELFENERGIESUSU)/SelfZ0Z0.o \
	$(SELFENERGIESUSU)/SelfAZ0.o $(SELFENERGIESUSU)/SelfAZ0ZeroMom.o $(SELFENERGIESALT)/SelfAA.o $(SELFENERGIESALT)/SelfWpWp.o $(SELFENERGIESALT)/SelfZ0Z0.o \
	$(SELFENERGIESALT)/SelfAZ0.o $(SELFENERGIESALT)/SelfAZ0ZeroMom.o $(SELFENERGIESUSU)/SelfA0A0.o \
	$(SELFENERGIESUSU)/SelfG0A0.o $(SELFENERGIESUSU)/SelfG0G0.o $(SELFENERGIESUSU)/SelfGpGp.o $(SELFENERGIESUSU)/SelfGpHp.o $(SELFENERGIESUSU)/Selfh0h0.o \
	$(SELFENERGIESUSU)/SelfHHh0.o $(SELFENERGIESUSU)/SelfHHHH.o $(SELFENERGIESUSU)/SelfHpHp.o $(SELFENERGIESALT)/SelfA0A0.o $(SELFENERGIESALT)/SelfG0A0.o \
	$(SELFENERGIESALT)/SelfG0G0.o $(SELFENERGIESALT)/SelfGpGp.o $(SELFENERGIESALT)/SelfGpHp.o $(SELFENERGIESALT)/Selfh0h0.o $(SELFENERGIESALT)/SelfHHh0.o \
	$(SELFENERGIESALT)/SelfHHHH.o $(SELFENERGIESALT)/SelfHpHp.o $(SELFENERGIESDERIV)/DSelfAA.o $(SELFENERGIESDERIV)/DSelfAALight.o $(SELFENERGIESDERIV)/DSelfWpWp.o \
	$(SELFENERGIESDERIV)/DSelfZ0Z0.o $(SELFENERGIESDERIV)/DSelfAZ0.o $(SELFENERGIESDERIV)/DSelfA0A0.o $(SELFENERGIESDERIV)/DSelfG0A0.o $(SELFENERGIESDERIV)/DSelfG0G0.o \
	$(SELFENERGIESDERIV)/DSelfGpGp.o $(SELFENERGIESDERIV)/DSelfGpHp.o $(SELFENERGIESDERIV)/DSelfHpHp.o $(SELFENERGIESDERIV)/DSelfh0h0.o $(SELFENERGIESDERIV)/DSelfHHh0.o \
	$(SELFENERGIESDERIV)/DSelfHHHH.o $(SELFENERGIESALT)/SelfHHh0Add.o $(SELFENERGIESALT)/SelfG0A0Add.o $(SELFENERGIESALT)/SelfGpHpAdd.o \
	$(TADPOLES)/TadHH.o $(TADPOLES)/Tadh0.o \
	$(SELFENERGIESUSU)/SelfNeuENeuELeft.o $(SELFENERGIESUSU)/SelfNeuENeuERight.o $(SELFENERGIESUSU)/SelfNeuENeuEScalar.o \
	$(SELFENERGIESUSU)/SelfNeuMNeuMLeft.o $(SELFENERGIESUSU)/SelfNeuMNeuMRight.o $(SELFENERGIESUSU)/SelfNeuMNeuMScalar.o \
	$(SELFENERGIESUSU)/SelfNeuTNeuTLeft.o $(SELFENERGIESUSU)/SelfNeuTNeuTRight.o $(SELFENERGIESUSU)/SelfNeuTNeuTScalar.o \
	$(SELFENERGIESUSU)/SelfElElLeft.o $(SELFENERGIESUSU)/SelfElElRight.o $(SELFENERGIESUSU)/SelfElElScalar.o \
	$(SELFENERGIESUSU)/SelfMuMuLeft.o $(SELFENERGIESUSU)/SelfMuMuRight.o $(SELFENERGIESUSU)/SelfMuMuScalar.o \
	$(SELFENERGIESUSU)/SelfTauTauLeft.o $(SELFENERGIESUSU)/SelfTauTauRight.o $(SELFENERGIESUSU)/SelfTauTauScalar.o \
	$(SELFENERGIESUSU)/SelfTauTauLeftQED.o $(SELFENERGIESUSU)/SelfTauTauRightQED.o $(SELFENERGIESUSU)/SelfTauTauScalarQED.o \
	$(SELFENERGIESUSU)/SelfTauTauLeftWeak.o $(SELFENERGIESUSU)/SelfTauTauRightWeak.o $(SELFENERGIESUSU)/SelfTauTauScalarWeak.o \
	$(SELFENERGIESUSU)/SelfDDLeft.o $(SELFENERGIESUSU)/SelfDDRight.o $(SELFENERGIESUSU)/SelfDDScalar.o \
	$(SELFENERGIESUSU)/SelfUULeft.o $(SELFENERGIESUSU)/SelfUURight.o $(SELFENERGIESUSU)/SelfUUScalar.o \
	$(SELFENERGIESUSU)/SelfSSLeft.o $(SELFENERGIESUSU)/SelfSSRight.o $(SELFENERGIESUSU)/SelfSSScalar.o \
	$(SELFENERGIESUSU)/SelfCCLeft.o $(SELFENERGIESUSU)/SelfCCRight.o $(SELFENERGIESUSU)/SelfCCScalar.o \
	$(SELFENERGIESUSU)/SelfBBLeft.o $(SELFENERGIESUSU)/SelfBBRight.o $(SELFENERGIESUSU)/SelfBBScalar.o \
	$(SELFENERGIESUSU)/SelfTTLeft.o $(SELFENERGIESUSU)/SelfTTRight.o $(SELFENERGIESUSU)/SelfTTScalar.o \
	$(SELFENERGIESUSU)/SelfUCLeft.o $(SELFENERGIESUSU)/SelfUCRight.o $(SELFENERGIESUSU)/SelfUCScalar.o \
	$(SELFENERGIESUSU)/SelfUTLeft.o $(SELFENERGIESUSU)/SelfUTRight.o $(SELFENERGIESUSU)/SelfUTScalar.o \
	$(SELFENERGIESUSU)/SelfCTLeft.o $(SELFENERGIESUSU)/SelfCTRight.o $(SELFENERGIESUSU)/SelfCTScalar.o \
	$(SELFENERGIESUSU)/SelfDSLeft.o $(SELFENERGIESUSU)/SelfDSRight.o $(SELFENERGIESUSU)/SelfDSScalar.o \
	$(SELFENERGIESUSU)/SelfDBLeft.o $(SELFENERGIESUSU)/SelfDBRight.o $(SELFENERGIESUSU)/SelfDBScalar.o \
	$(SELFENERGIESUSU)/SelfSBLeft.o $(SELFENERGIESUSU)/SelfSBRight.o $(SELFENERGIESUSU)/SelfSBScalar.o \
	$(SELFENERGIESALT)/SelfNeuENeuELeft.o $(SELFENERGIESALT)/SelfNeuENeuERight.o $(SELFENERGIESALT)/SelfNeuENeuEScalar.o \
	$(SELFENERGIESALT)/SelfNeuMNeuMLeft.o $(SELFENERGIESALT)/SelfNeuMNeuMRight.o $(SELFENERGIESALT)/SelfNeuMNeuMScalar.o \
	$(SELFENERGIESALT)/SelfNeuTNeuTLeft.o $(SELFENERGIESALT)/SelfNeuTNeuTRight.o $(SELFENERGIESALT)/SelfNeuTNeuTScalar.o \
	$(SELFENERGIESALT)/SelfElElLeft.o $(SELFENERGIESALT)/SelfElElRight.o $(SELFENERGIESALT)/SelfElElScalar.o \
	$(SELFENERGIESALT)/SelfMuMuLeft.o $(SELFENERGIESALT)/SelfMuMuRight.o $(SELFENERGIESALT)/SelfMuMuScalar.o \
	$(SELFENERGIESALT)/SelfTauTauLeft.o $(SELFENERGIESALT)/SelfTauTauRight.o $(SELFENERGIESALT)/SelfTauTauScalar.o \
	$(SELFENERGIESALT)/SelfTauTauLeftQED.o $(SELFENERGIESALT)/SelfTauTauRightQED.o $(SELFENERGIESALT)/SelfTauTauScalarQED.o \
	$(SELFENERGIESALT)/SelfTauTauLeftWeak.o $(SELFENERGIESALT)/SelfTauTauRightWeak.o $(SELFENERGIESALT)/SelfTauTauScalarWeak.o \
	$(SELFENERGIESALT)/SelfDDLeft.o $(SELFENERGIESALT)/SelfDDRight.o $(SELFENERGIESALT)/SelfDDScalar.o \
	$(SELFENERGIESALT)/SelfUULeft.o $(SELFENERGIESALT)/SelfUURight.o $(SELFENERGIESALT)/SelfUUScalar.o \
	$(SELFENERGIESALT)/SelfSSLeft.o $(SELFENERGIESALT)/SelfSSRight.o $(SELFENERGIESALT)/SelfSSScalar.o \
	$(SELFENERGIESALT)/SelfCCLeft.o $(SELFENERGIESALT)/SelfCCRight.o $(SELFENERGIESALT)/SelfCCScalar.o \
	$(SELFENERGIESALT)/SelfBBLeft.o $(SELFENERGIESALT)/SelfBBRight.o $(SELFENERGIESALT)/SelfBBScalar.o \
	$(SELFENERGIESALT)/SelfTTLeft.o $(SELFENERGIESALT)/SelfTTRight.o $(SELFENERGIESALT)/SelfTTScalar.o \
	$(SELFENERGIESALT)/SelfUCLeft.o $(SELFENERGIESALT)/SelfUCRight.o $(SELFENERGIESALT)/SelfUCScalar.o \
	$(SELFENERGIESALT)/SelfUTLeft.o $(SELFENERGIESALT)/SelfUTRight.o $(SELFENERGIESALT)/SelfUTScalar.o \
	$(SELFENERGIESALT)/SelfCTLeft.o $(SELFENERGIESALT)/SelfCTRight.o $(SELFENERGIESALT)/SelfCTScalar.o \
	$(SELFENERGIESALT)/SelfDSLeft.o $(SELFENERGIESALT)/SelfDSRight.o $(SELFENERGIESALT)/SelfDSScalar.o \
	$(SELFENERGIESALT)/SelfDBLeft.o $(SELFENERGIESALT)/SelfDBRight.o $(SELFENERGIESALT)/SelfDBScalar.o \
	$(SELFENERGIESALT)/SelfSBLeft.o $(SELFENERGIESALT)/SelfSBRight.o $(SELFENERGIESALT)/SelfSBScalar.o \
	$(SELFENERGIESDERIV)/DSelfNeuENeuELeft.o $(SELFENERGIESDERIV)/DSelfNeuENeuERight.o $(SELFENERGIESDERIV)/DSelfNeuENeuEScalar.o \
	$(SELFENERGIESDERIV)/DSelfNeuMNeuMLeft.o $(SELFENERGIESDERIV)/DSelfNeuMNeuMRight.o $(SELFENERGIESDERIV)/DSelfNeuMNeuMScalar.o \
	$(SELFENERGIESDERIV)/DSelfNeuTNeuTLeft.o $(SELFENERGIESDERIV)/DSelfNeuTNeuTRight.o $(SELFENERGIESDERIV)/DSelfNeuTNeuTScalar.o \
	$(SELFENERGIESDERIV)/DSelfElElLeft.o $(SELFENERGIESDERIV)/DSelfElElRight.o $(SELFENERGIESDERIV)/DSelfElElScalar.o \
	$(SELFENERGIESDERIV)/DSelfMuMuLeft.o $(SELFENERGIESDERIV)/DSelfMuMuRight.o $(SELFENERGIESDERIV)/DSelfMuMuScalar.o \
	$(SELFENERGIESDERIV)/DSelfTauTauLeft.o $(SELFENERGIESDERIV)/DSelfTauTauRight.o $(SELFENERGIESDERIV)/DSelfTauTauScalar.o \
	$(SELFENERGIESDERIV)/DSelfTauTauLeftQED.o $(SELFENERGIESDERIV)/DSelfTauTauRightQED.o $(SELFENERGIESDERIV)/DSelfTauTauScalarQED.o \
	$(SELFENERGIESDERIV)/DSelfTauTauLeftWeak.o $(SELFENERGIESDERIV)/DSelfTauTauRightWeak.o $(SELFENERGIESDERIV)/DSelfTauTauScalarWeak.o \
	$(SELFENERGIESDERIV)/DSelfDDLeft.o $(SELFENERGIESDERIV)/DSelfDDRight.o $(SELFENERGIESDERIV)/DSelfDDScalar.o \
	$(SELFENERGIESDERIV)/DSelfUULeft.o $(SELFENERGIESDERIV)/DSelfUURight.o $(SELFENERGIESDERIV)/DSelfUUScalar.o \
	$(SELFENERGIESDERIV)/DSelfSSLeft.o $(SELFENERGIESDERIV)/DSelfSSRight.o $(SELFENERGIESDERIV)/DSelfSSScalar.o \
	$(SELFENERGIESDERIV)/DSelfCCLeft.o $(SELFENERGIESDERIV)/DSelfCCRight.o $(SELFENERGIESDERIV)/DSelfCCScalar.o \
	$(SELFENERGIESDERIV)/DSelfBBLeft.o $(SELFENERGIESDERIV)/DSelfBBRight.o $(SELFENERGIESDERIV)/DSelfBBScalar.o \
	$(SELFENERGIESDERIV)/DSelfTTLeft.o $(SELFENERGIESDERIV)/DSelfTTRight.o $(SELFENERGIESDERIV)/DSelfTTScalar.o \
	$(SELFENERGIESDERIV)/DSelfUCLeft.o $(SELFENERGIESDERIV)/DSelfUCRight.o $(SELFENERGIESDERIV)/DSelfUCScalar.o \
	$(SELFENERGIESDERIV)/DSelfUTLeft.o $(SELFENERGIESDERIV)/DSelfUTRight.o $(SELFENERGIESDERIV)/DSelfUTScalar.o \
	$(SELFENERGIESDERIV)/DSelfCTLeft.o $(SELFENERGIESDERIV)/DSelfCTRight.o $(SELFENERGIESDERIV)/DSelfCTScalar.o \
	$(SELFENERGIESDERIV)/DSelfDSLeft.o $(SELFENERGIESDERIV)/DSelfDSRight.o $(SELFENERGIESDERIV)/DSelfDSScalar.o \
	$(SELFENERGIESDERIV)/DSelfDBLeft.o $(SELFENERGIESDERIV)/DSelfDBRight.o $(SELFENERGIESDERIV)/DSelfDBScalar.o \
	$(SELFENERGIESDERIV)/DSelfSBLeft.o $(SELFENERGIESDERIV)/DSelfSBRight.o $(SELFENERGIESDERIV)/DSelfSBScalar.o \
	$(PROCESSDEPENDENTSCHEME)/A0toTauPTauMProcDepVC.o $(PROCESSDEPENDENTSCHEME)/HHtoTauPTauMProcDepVC.o $(PROCESSDEPENDENTSCHEME)/h0toTauPTauMProcDepVC.o \
	$(PROCESSA0TOBBBAR)/TreeLevelWidthRed.o $(PROCESSA0TOBBBAR)/NLOWidthRed.o $(PROCESSA0TOBBBAR)/NLOTadWidthRed.o $(PROCESSA0TOBBBAR)/Counterterm.o $(PROCESSA0TOBBBAR)/RealCorrections.o \
	$(PROCESSA0TOCCBAR)/TreeLevelWidthRed.o $(PROCESSA0TOCCBAR)/NLOWidthRed.o $(PROCESSA0TOCCBAR)/NLOTadWidthRed.o $(PROCESSA0TOCCBAR)/Counterterm.o $(PROCESSA0TOCCBAR)/RealCorrections.o \
	$(PROCESSA0TODDBAR)/TreeLevelWidthRed.o $(PROCESSA0TODDBAR)/NLOWidthRed.o $(PROCESSA0TODDBAR)/NLOTadWidthRed.o $(PROCESSA0TODDBAR)/Counterterm.o $(PROCESSA0TODDBAR)/RealCorrections.o \
	$(PROCESSA0TOELELBAR)/TreeLevelWidthRed.o $(PROCESSA0TOELELBAR)/NLOWidthRed.o $(PROCESSA0TOELELBAR)/NLOTadWidthRed.o $(PROCESSA0TOELELBAR)/Counterterm.o $(PROCESSA0TOELELBAR)/RealCorrections.o \
	$(PROCESSA0TOHHZ0)/TreeLevelWidthRed.o $(PROCESSA0TOHHZ0)/NLOWidthRed.o $(PROCESSA0TOHHZ0)/NLOTadWidthRed.o $(PROCESSA0TOHHZ0)/Counterterm.o $(PROCESSA0TOHHZ0)/RealCorrections.o \
	$(PROCESSA0TOHMWP)/TreeLevelWidthRed.o $(PROCESSA0TOHMWP)/NLOWidthRed.o $(PROCESSA0TOHMWP)/NLOTadWidthRed.o $(PROCESSA0TOHMWP)/Counterterm.o $(PROCESSA0TOHMWP)/RealCorrections.o \
	$(PROCESSA0TOMUMUBAR)/TreeLevelWidthRed.o $(PROCESSA0TOMUMUBAR)/NLOWidthRed.o $(PROCESSA0TOMUMUBAR)/NLOTadWidthRed.o $(PROCESSA0TOMUMUBAR)/Counterterm.o $(PROCESSA0TOMUMUBAR)/RealCorrections.o \
	$(PROCESSA0TOSSBAR)/TreeLevelWidthRed.o $(PROCESSA0TOSSBAR)/NLOWidthRed.o $(PROCESSA0TOSSBAR)/NLOTadWidthRed.o $(PROCESSA0TOSSBAR)/Counterterm.o $(PROCESSA0TOSSBAR)/RealCorrections.o \
	$(PROCESSA0TOTAUTAUBAR)/TreeLevelWidthRed.o $(PROCESSA0TOTAUTAUBAR)/NLOWidthRed.o $(PROCESSA0TOTAUTAUBAR)/NLOTadWidthRed.o $(PROCESSA0TOTAUTAUBAR)/Counterterm.o $(PROCESSA0TOTAUTAUBAR)/RealCorrections.o \
	$(PROCESSA0TOTTBAR)/TreeLevelWidthRed.o $(PROCESSA0TOTTBAR)/NLOWidthRed.o $(PROCESSA0TOTTBAR)/NLOTadWidthRed.o $(PROCESSA0TOTTBAR)/Counterterm.o $(PROCESSA0TOTTBAR)/RealCorrections.o \
	$(PROCESSA0TOUUBAR)/TreeLevelWidthRed.o $(PROCESSA0TOUUBAR)/NLOWidthRed.o $(PROCESSA0TOUUBAR)/NLOTadWidthRed.o $(PROCESSA0TOUUBAR)/Counterterm.o $(PROCESSA0TOUUBAR)/RealCorrections.o \
	$(PROCESSA0TOZ0H0)/TreeLevelWidthRed.o $(PROCESSA0TOZ0H0)/NLOWidthRed.o $(PROCESSA0TOZ0H0)/NLOTadWidthRed.o $(PROCESSA0TOZ0H0)/Counterterm.o $(PROCESSA0TOZ0H0)/RealCorrections.o \
	$(PROCESSH0TOA0A0)/TreeLevelWidthRed.o $(PROCESSH0TOA0A0)/NLOWidthRed.o $(PROCESSH0TOA0A0)/NLOTadWidthRed.o $(PROCESSH0TOA0A0)/Counterterm.o $(PROCESSH0TOA0A0)/RealCorrections.o \
	$(PROCESSH0TOA0Z0)/TreeLevelWidthRed.o $(PROCESSH0TOA0Z0)/NLOWidthRed.o $(PROCESSH0TOA0Z0)/NLOTadWidthRed.o $(PROCESSH0TOA0Z0)/Counterterm.o $(PROCESSH0TOA0Z0)/RealCorrections.o \
	$(PROCESSH0TOBBBAR)/TreeLevelWidthRed.o $(PROCESSH0TOBBBAR)/NLOWidthRed.o $(PROCESSH0TOBBBAR)/NLOTadWidthRed.o $(PROCESSH0TOBBBAR)/Counterterm.o $(PROCESSH0TOBBBAR)/RealCorrections.o \
	$(PROCESSH0TOCCBAR)/TreeLevelWidthRed.o $(PROCESSH0TOCCBAR)/NLOWidthRed.o $(PROCESSH0TOCCBAR)/NLOTadWidthRed.o $(PROCESSH0TOCCBAR)/Counterterm.o $(PROCESSH0TOCCBAR)/RealCorrections.o \
	$(PROCESSH0TODDBAR)/TreeLevelWidthRed.o $(PROCESSH0TODDBAR)/NLOWidthRed.o $(PROCESSH0TODDBAR)/NLOTadWidthRed.o $(PROCESSH0TODDBAR)/Counterterm.o $(PROCESSH0TODDBAR)/RealCorrections.o \
	$(PROCESSH0TOELELBAR)/TreeLevelWidthRed.o $(PROCESSH0TOELELBAR)/NLOWidthRed.o $(PROCESSH0TOELELBAR)/NLOTadWidthRed.o $(PROCESSH0TOELELBAR)/Counterterm.o $(PROCESSH0TOELELBAR)/RealCorrections.o \
	$(PROCESSH0TOHHHH)/TreeLevelWidthRed.o $(PROCESSH0TOHHHH)/NLOWidthRed.o $(PROCESSH0TOHHHH)/NLOTadWidthRed.o $(PROCESSH0TOHHHH)/Counterterm.o $(PROCESSH0TOHHHH)/RealCorrections.o \
	$(PROCESSH0TOHMHP)/TreeLevelWidthRed.o $(PROCESSH0TOHMHP)/NLOWidthRed.o $(PROCESSH0TOHMHP)/NLOTadWidthRed.o $(PROCESSH0TOHMHP)/Counterterm.o $(PROCESSH0TOHMHP)/RealCorrections.o \
	$(PROCESSH0TOHPWM)/TreeLevelWidthRed.o $(PROCESSH0TOHPWM)/NLOWidthRed.o $(PROCESSH0TOHPWM)/NLOTadWidthRed.o $(PROCESSH0TOHPWM)/Counterterm.o $(PROCESSH0TOHPWM)/RealCorrections.o \
	$(PROCESSH0TOMUMUBAR)/TreeLevelWidthRed.o $(PROCESSH0TOMUMUBAR)/NLOWidthRed.o $(PROCESSH0TOMUMUBAR)/NLOTadWidthRed.o $(PROCESSH0TOMUMUBAR)/Counterterm.o $(PROCESSH0TOMUMUBAR)/RealCorrections.o \
	$(PROCESSH0TOSSBAR)/TreeLevelWidthRed.o $(PROCESSH0TOSSBAR)/NLOWidthRed.o $(PROCESSH0TOSSBAR)/NLOTadWidthRed.o $(PROCESSH0TOSSBAR)/Counterterm.o $(PROCESSH0TOSSBAR)/RealCorrections.o \
	$(PROCESSH0TOTAUTAUBAR)/TreeLevelWidthRed.o $(PROCESSH0TOTAUTAUBAR)/NLOWidthRed.o $(PROCESSH0TOTAUTAUBAR)/NLOTadWidthRed.o $(PROCESSH0TOTAUTAUBAR)/Counterterm.o $(PROCESSH0TOTAUTAUBAR)/RealCorrections.o \
	$(PROCESSH0TOTTBAR)/TreeLevelWidthRed.o $(PROCESSH0TOTTBAR)/NLOWidthRed.o $(PROCESSH0TOTTBAR)/NLOTadWidthRed.o $(PROCESSH0TOTTBAR)/Counterterm.o $(PROCESSH0TOTTBAR)/RealCorrections.o \
	$(PROCESSH0TOUUBAR)/TreeLevelWidthRed.o $(PROCESSH0TOUUBAR)/NLOWidthRed.o $(PROCESSH0TOUUBAR)/NLOTadWidthRed.o $(PROCESSH0TOUUBAR)/Counterterm.o $(PROCESSH0TOUUBAR)/RealCorrections.o \
	$(PROCESSH0TOWMWP)/TreeLevelWidthRed.o $(PROCESSH0TOWMWP)/NLOWidthRed.o $(PROCESSH0TOWMWP)/NLOTadWidthRed.o $(PROCESSH0TOWMWP)/Counterterm.o $(PROCESSH0TOWMWP)/RealCorrections.o \
	$(PROCESSH0TOZ0Z0)/TreeLevelWidthRed.o $(PROCESSH0TOZ0Z0)/NLOWidthRed.o $(PROCESSH0TOZ0Z0)/NLOTadWidthRed.o $(PROCESSH0TOZ0Z0)/Counterterm.o $(PROCESSH0TOZ0Z0)/RealCorrections.o \
	$(PROCESSHHTOA0A0)/TreeLevelWidthRed.o $(PROCESSHHTOA0A0)/NLOWidthRed.o $(PROCESSHHTOA0A0)/NLOTadWidthRed.o $(PROCESSHHTOA0A0)/Counterterm.o $(PROCESSHHTOA0A0)/RealCorrections.o \
	$(PROCESSHHTOA0Z0)/TreeLevelWidthRed.o $(PROCESSHHTOA0Z0)/NLOWidthRed.o $(PROCESSHHTOA0Z0)/NLOTadWidthRed.o $(PROCESSHHTOA0Z0)/Counterterm.o $(PROCESSHHTOA0Z0)/RealCorrections.o \
	$(PROCESSHHTOBBBAR)/TreeLevelWidthRed.o $(PROCESSHHTOBBBAR)/NLOWidthRed.o $(PROCESSHHTOBBBAR)/NLOTadWidthRed.o $(PROCESSHHTOBBBAR)/Counterterm.o $(PROCESSHHTOBBBAR)/RealCorrections.o \
	$(PROCESSHHTOCCBAR)/TreeLevelWidthRed.o $(PROCESSHHTOCCBAR)/NLOWidthRed.o $(PROCESSHHTOCCBAR)/NLOTadWidthRed.o $(PROCESSHHTOCCBAR)/Counterterm.o $(PROCESSHHTOCCBAR)/RealCorrections.o \
	$(PROCESSHHTODDBAR)/TreeLevelWidthRed.o $(PROCESSHHTODDBAR)/NLOWidthRed.o $(PROCESSHHTODDBAR)/NLOTadWidthRed.o $(PROCESSHHTODDBAR)/Counterterm.o $(PROCESSHHTODDBAR)/RealCorrections.o \
	$(PROCESSHHTOELELBAR)/TreeLevelWidthRed.o $(PROCESSHHTOELELBAR)/NLOWidthRed.o $(PROCESSHHTOELELBAR)/NLOTadWidthRed.o $(PROCESSHHTOELELBAR)/Counterterm.o $(PROCESSHHTOELELBAR)/RealCorrections.o \
	$(PROCESSHHTOH0H0)/TreeLevelWidthRed.o $(PROCESSHHTOH0H0)/NLOWidthRed.o $(PROCESSHHTOH0H0)/NLOTadWidthRed.o $(PROCESSHHTOH0H0)/Counterterm.o $(PROCESSHHTOH0H0)/RealCorrections.o \
	$(PROCESSHHTOHMHP)/TreeLevelWidthRed.o $(PROCESSHHTOHMHP)/NLOWidthRed.o $(PROCESSHHTOHMHP)/NLOTadWidthRed.o $(PROCESSHHTOHMHP)/Counterterm.o $(PROCESSHHTOHMHP)/RealCorrections.o \
	$(PROCESSHHTOHPWM)/TreeLevelWidthRed.o $(PROCESSHHTOHPWM)/NLOWidthRed.o $(PROCESSHHTOHPWM)/NLOTadWidthRed.o $(PROCESSHHTOHPWM)/Counterterm.o $(PROCESSHHTOHPWM)/RealCorrections.o \
	$(PROCESSHHTOMUMUBAR)/TreeLevelWidthRed.o $(PROCESSHHTOMUMUBAR)/NLOWidthRed.o $(PROCESSHHTOMUMUBAR)/NLOTadWidthRed.o $(PROCESSHHTOMUMUBAR)/Counterterm.o $(PROCESSHHTOMUMUBAR)/RealCorrections.o \
	$(PROCESSHHTOSSBAR)/TreeLevelWidthRed.o $(PROCESSHHTOSSBAR)/NLOWidthRed.o $(PROCESSHHTOSSBAR)/NLOTadWidthRed.o $(PROCESSHHTOSSBAR)/Counterterm.o $(PROCESSHHTOSSBAR)/RealCorrections.o \
	$(PROCESSHHTOTAUTAUBAR)/TreeLevelWidthRed.o $(PROCESSHHTOTAUTAUBAR)/NLOWidthRed.o $(PROCESSHHTOTAUTAUBAR)/NLOTadWidthRed.o $(PROCESSHHTOTAUTAUBAR)/Counterterm.o $(PROCESSHHTOTAUTAUBAR)/RealCorrections.o \
	$(PROCESSHHTOTTBAR)/TreeLevelWidthRed.o $(PROCESSHHTOTTBAR)/NLOWidthRed.o $(PROCESSHHTOTTBAR)/NLOTadWidthRed.o $(PROCESSHHTOTTBAR)/Counterterm.o $(PROCESSHHTOTTBAR)/RealCorrections.o \
	$(PROCESSHHTOUUBAR)/TreeLevelWidthRed.o $(PROCESSHHTOUUBAR)/NLOWidthRed.o $(PROCESSHHTOUUBAR)/NLOTadWidthRed.o $(PROCESSHHTOUUBAR)/Counterterm.o $(PROCESSHHTOUUBAR)/RealCorrections.o \
	$(PROCESSHHTOWMWP)/TreeLevelWidthRed.o $(PROCESSHHTOWMWP)/NLOWidthRed.o $(PROCESSHHTOWMWP)/NLOTadWidthRed.o $(PROCESSHHTOWMWP)/Counterterm.o $(PROCESSHHTOWMWP)/RealCorrections.o \
	$(PROCESSHHTOZ0Z0)/TreeLevelWidthRed.o $(PROCESSHHTOZ0Z0)/NLOWidthRed.o $(PROCESSHHTOZ0Z0)/NLOTadWidthRed.o $(PROCESSHHTOZ0Z0)/Counterterm.o $(PROCESSHHTOZ0Z0)/RealCorrections.o \
	$(PROCESSHPTOA0WP)/TreeLevelWidthRed.o $(PROCESSHPTOA0WP)/NLOWidthRed.o $(PROCESSHPTOA0WP)/NLOTadWidthRed.o $(PROCESSHPTOA0WP)/Counterterm.o $(PROCESSHPTOA0WP)/RealCorrections.o \
	$(PROCESSHPTOBBARC)/TreeLevelWidthRed.o $(PROCESSHPTOBBARC)/NLOWidthRed.o $(PROCESSHPTOBBARC)/NLOTadWidthRed.o $(PROCESSHPTOBBARC)/Counterterm.o $(PROCESSHPTOBBARC)/RealCorrections.o \
	$(PROCESSHPTOBBART)/TreeLevelWidthRed.o $(PROCESSHPTOBBART)/NLOWidthRed.o $(PROCESSHPTOBBART)/NLOTadWidthRed.o $(PROCESSHPTOBBART)/Counterterm.o $(PROCESSHPTOBBART)/RealCorrections.o \
	$(PROCESSHPTOBBARU)/TreeLevelWidthRed.o $(PROCESSHPTOBBARU)/NLOWidthRed.o $(PROCESSHPTOBBARU)/NLOTadWidthRed.o $(PROCESSHPTOBBARU)/Counterterm.o $(PROCESSHPTOBBARU)/RealCorrections.o \
	$(PROCESSHPTOCDBAR)/TreeLevelWidthRed.o $(PROCESSHPTOCDBAR)/NLOWidthRed.o $(PROCESSHPTOCDBAR)/NLOTadWidthRed.o $(PROCESSHPTOCDBAR)/Counterterm.o $(PROCESSHPTOCDBAR)/RealCorrections.o \
	$(PROCESSHPTOCSBAR)/TreeLevelWidthRed.o $(PROCESSHPTOCSBAR)/NLOWidthRed.o $(PROCESSHPTOCSBAR)/NLOTadWidthRed.o $(PROCESSHPTOCSBAR)/Counterterm.o $(PROCESSHPTOCSBAR)/RealCorrections.o \
	$(PROCESSHPTODBART)/TreeLevelWidthRed.o $(PROCESSHPTODBART)/NLOWidthRed.o $(PROCESSHPTODBART)/NLOTadWidthRed.o $(PROCESSHPTODBART)/Counterterm.o $(PROCESSHPTODBART)/RealCorrections.o \
	$(PROCESSHPTODBARU)/TreeLevelWidthRed.o $(PROCESSHPTODBARU)/NLOWidthRed.o $(PROCESSHPTODBARU)/NLOTadWidthRed.o $(PROCESSHPTODBARU)/Counterterm.o $(PROCESSHPTODBARU)/RealCorrections.o \
	$(PROCESSHPTOELBARNEUE)/TreeLevelWidthRed.o $(PROCESSHPTOELBARNEUE)/NLOWidthRed.o $(PROCESSHPTOELBARNEUE)/NLOTadWidthRed.o $(PROCESSHPTOELBARNEUE)/Counterterm.o $(PROCESSHPTOELBARNEUE)/RealCorrections.o \
	$(PROCESSHPTOHHWP)/TreeLevelWidthRed.o $(PROCESSHPTOHHWP)/NLOWidthRed.o $(PROCESSHPTOHHWP)/NLOTadWidthRed.o $(PROCESSHPTOHHWP)/Counterterm.o $(PROCESSHPTOHHWP)/RealCorrections.o \
	$(PROCESSHPTOMUBARNEUM)/TreeLevelWidthRed.o $(PROCESSHPTOMUBARNEUM)/NLOWidthRed.o $(PROCESSHPTOMUBARNEUM)/NLOTadWidthRed.o $(PROCESSHPTOMUBARNEUM)/Counterterm.o $(PROCESSHPTOMUBARNEUM)/RealCorrections.o \
	$(PROCESSHPTONEUTTAUBAR)/TreeLevelWidthRed.o $(PROCESSHPTONEUTTAUBAR)/NLOWidthRed.o $(PROCESSHPTONEUTTAUBAR)/NLOTadWidthRed.o $(PROCESSHPTONEUTTAUBAR)/Counterterm.o $(PROCESSHPTONEUTTAUBAR)/RealCorrections.o \
	$(PROCESSHPTOSBART)/TreeLevelWidthRed.o $(PROCESSHPTOSBART)/NLOWidthRed.o $(PROCESSHPTOSBART)/NLOTadWidthRed.o $(PROCESSHPTOSBART)/Counterterm.o $(PROCESSHPTOSBART)/RealCorrections.o \
	$(PROCESSHPTOSBARU)/TreeLevelWidthRed.o $(PROCESSHPTOSBARU)/NLOWidthRed.o $(PROCESSHPTOSBARU)/NLOTadWidthRed.o $(PROCESSHPTOSBARU)/Counterterm.o $(PROCESSHPTOSBARU)/RealCorrections.o \
	$(PROCESSHPTOWPH0)/TreeLevelWidthRed.o $(PROCESSHPTOWPH0)/NLOWidthRed.o $(PROCESSHPTOWPH0)/NLOTadWidthRed.o $(PROCESSHPTOWPH0)/Counterterm.o $(PROCESSHPTOWPH0)/RealCorrections.o \
	counterterms.o $(PARAMETERS)/getParameters.o electroweakCorrections.o $(LFlags) -o electroweakCorrections.exe

clean:
	rm -f *.o
	rm -f $(SELFENERGIESALT)/*.o
	rm -f $(SELFENERGIESUSU)/*.o
	rm -f $(SELFENERGIESDERIV)/*.o
	rm -f $(PROCESSDEPENDENTSCHEME)/*.o
	rm -f $(TADPOLES)/*.o
	rm -f $(PROCESSA0TOBBBAR)/*.o
	rm -f $(PROCESSA0TOCCBAR)/*.o
	rm -f $(PROCESSA0TODDBAR)/*.o
	rm -f $(PROCESSA0TOELELBAR)/*.o
	rm -f $(PROCESSA0TOHHZ0)/*.o
	rm -f $(PROCESSA0TOHMWP)/*.o
	rm -f $(PROCESSA0TOMUMUBAR)/*.o
	rm -f $(PROCESSA0TOSSBAR)/*.o
	rm -f $(PROCESSA0TOTAUTAUBAR)/*.o
	rm -f $(PROCESSA0TOTTBAR)/*.o
	rm -f $(PROCESSA0TOUUBAR)/*.o
	rm -f $(PROCESSA0TOZ0H0)/*.o
	rm -f $(PROCESSH0TOA0A0)/*.o
	rm -f $(PROCESSH0TOA0Z0)/*.o
	rm -f $(PROCESSH0TOBBBAR)/*.o
	rm -f $(PROCESSH0TOCCBAR)/*.o
	rm -f $(PROCESSH0TODDBAR)/*.o
	rm -f $(PROCESSH0TOELELBAR)/*.o
	rm -f $(PROCESSH0TOHHHH)/*.o
	rm -f $(PROCESSH0TOHMHP)/*.o
	rm -f $(PROCESSH0TOHPWM)/*.o
	rm -f $(PROCESSH0TOMUMUBAR)/*.o
	rm -f $(PROCESSH0TOSSBAR)/*.o
	rm -f $(PROCESSH0TOTAUTAUBAR)/*.o
	rm -f $(PROCESSH0TOTTBAR)/*.o
	rm -f $(PROCESSH0TOUUBAR)/*.o
	rm -f $(PROCESSH0TOWMWP)/*.o
	rm -f $(PROCESSH0TOZ0Z0)/*.o
	rm -f $(PROCESSHHTOA0A0)/*.o
	rm -f $(PROCESSHHTOA0Z0)/*.o
	rm -f $(PROCESSHHTOBBBAR)/*.o
	rm -f $(PROCESSHHTOCCBAR)/*.o
	rm -f $(PROCESSHHTODDBAR)/*.o
	rm -f $(PROCESSHHTOELELBAR)/*.o
	rm -f $(PROCESSHHTOH0H0)/*.o
	rm -f $(PROCESSHHTOHMHP)/*.o
	rm -f $(PROCESSHHTOHPWM)/*.o
	rm -f $(PROCESSHHTOMUMUBAR)/*.o
	rm -f $(PROCESSHHTOSSBAR)/*.o
	rm -f $(PROCESSHHTOTAUTAUBAR)/*.o
	rm -f $(PROCESSHHTOTTBAR)/*.o
	rm -f $(PROCESSHHTOUUBAR)/*.o
	rm -f $(PROCESSHHTOWMWP)/*.o
	rm -f $(PROCESSHHTOZ0Z0)/*.o
	rm -f $(PROCESSHPTOA0WP)/*.o
	rm -f $(PROCESSHPTOBBARC)/*.o
	rm -f $(PROCESSHPTOBBART)/*.o
	rm -f $(PROCESSHPTOBBARU)/*.o
	rm -f $(PROCESSHPTOCDBAR)/*.o
	rm -f $(PROCESSHPTOCSBAR)/*.o
	rm -f $(PROCESSHPTODBART)/*.o
	rm -f $(PROCESSHPTODBARU)/*.o
	rm -f $(PROCESSHPTOELBARNEUE)/*.o
	rm -f $(PROCESSHPTOHHWP)/*.o
	rm -f $(PROCESSHPTOMUBARNEUM)/*.o
	rm -f $(PROCESSHPTONEUTTAUBAR)/*.o
	rm -f $(PROCESSHPTOSBART)/*.o
	rm -f $(PROCESSHPTOSBARU)/*.o
	rm -f $(PROCESSHPTOWPH0)/*.o
